apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kube-cleaner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-cleaner.labels" . | nindent 4 }}
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

{{- if .Values.watchNamespace }}
{{- include "kube-cleaner.role.rules.application" . | nindent 2 }}
{{- end }}