apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kube-cleaner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-cleaner.labels" . | nindent 4 }}
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [dev.superwise.ai]
    resources: ["*"]
    verbs: [list, watch, patch]

{{- if .Values.watchNamespace }}
{{- include "kube-cleaner.role.rules.application" . | nindent 2 }}
{{- end }}