apiVersion: dev.superwise.ai/v1alpha1
kind: ClusterCleanupPolicy
metadata:
  name: test
spec:
  rules:
    pods:
      - failed: 10s
        succeeded: 1m
        labelSelector:
          job-name: pi2
