apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustercleanuppolicies.dev.superwise.ai
spec:
  scope: Cluster
  group: dev.superwise.ai
  names:
    kind: ClusterCleanupPolicy
    plural: clustercleanuppolicies
    singular: clustercleanuppolicy
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                rules:
                  properties:
                    pods:
                      items:
                        properties:
                          failed:
                            type: string
                          labelSelector:
                            type: object
                          succeeded:
                            type: string
                          includeTerminated:
                            type: boolean
                          dryRun:
                            type: boolean
                        type: object
                      type: array
                  type: object
              required:
                - rules
              type: object
          required:
            - metadata
            - spec
          type: object
      served: true
      storage: true
